import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronDown, ClipboardList, ExternalLink, LayoutDashboard, LogOut, Menu, Package, RefreshCw, Search, ShoppingBag, Users, XCircle } from 'lucide-react';
import { supabaseRest } from './lib/supabase';
import AdminProductManager from './admin-product-manager';

type Order={id:number;customer_name:string;customer_phone:string;items:any[];subtotal:number;delivery_fee:number;total:number;status:string;payment_method:string;created_at:string;city:string;state:string};
const money=(n:number)=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const statuses=['Aguardando pagamento','Pago','Em preparação','Enviado','Entregue','Cancelado'];
export default function AdminFixed(){
 const [orders,setOrders]=useState<Order[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [tab,setTab]=useState<'dashboard'|'orders'|'customers'|'products'>('dashboard'); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<Order|null>(null); const [saving,setSaving]=useState<number|null>(null); const [mobile,setMobile]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const rows=await supabaseRest<Order[]>('orders?select=*&order=created_at.desc');setOrders(rows||[])}catch(e){console.error(e);setError('Não foi possível carregar os pedidos. Verifique as políticas do Supabase.')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const updateStatus=async(id:number,status:string)=>{setSaving(id);try{await supabaseRest(`orders?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})});setOrders(xs=>xs.map(o=>o.id===id?{...o,status}:o));if(selected?.id===id)setSelected({...selected,status})}catch(e){console.error(e);setError('Não foi possível atualizar o status.')}finally{setSaving(null)}};
 const filtered=useMemo(()=>orders.filter(o=>`${o.id} ${o.customer_name} ${o.customer_phone} ${o.status}`.toLowerCase().includes(search.toLowerCase())),[orders,search]);
 const total=orders.reduce((s,o)=>s+Number(o.total||0),0), pending=orders.filter(o=>!['Entregue','Cancelado'].includes(o.status)).length, customers=new Set(orders.map(o=>o.customer_phone||o.customer_name)).size;
 const exit=()=>{localStorage.removeItem('petviva_admin');location.reload()};
 const title=tab==='dashboard'?'Visão geral':tab==='orders'?'Pedidos':tab==='customers'?'Clientes':'Produtos';
 return <div className="pv-admin"><aside className={`pv-side ${mobile?'open':''}`}><div className="pv-brand"><span>🐾</span><b>PetViva</b><small>Admin</small></div><nav>{[['dashboard','Visão geral',LayoutDashboard],['orders','Pedidos',ClipboardList],['customers','Clientes',Users],['products','Produtos',Package]].map(([id,label,Icon]:any)=><button className={tab===id?'active':''} onClick={()=>{setTab(id);setMobile(false)}} key={id}><Icon size={18}/><span>{label}</span></button>)}</nav><button className="pv-exit" onClick={exit}><LogOut size={18}/> Sair</button></aside><main className="pv-main"><header className="pv-top"><button className="pv-mobile" onClick={()=>setMobile(!mobile)}><Menu/></button><div><small>Painel administrativo</small><h1>{title}</h1></div><div className="pv-top-actions"><button onClick={load} title="Atualizar"><RefreshCw size={18}/></button><button onClick={exit} title="Sair"><LogOut size={18}/></button></div></header><div className="pv-content">{error&&<div className="pv-error"><XCircle size={18}/>{error}</div>}
 {tab==='dashboard'&&<><div className="pv-metrics"><Metric icon="💰" label="Faturamento" value={money(total)}/><Metric icon="🛒" label="Pedidos" value={String(orders.length)}/><Metric icon="⏳" label="Em andamento" value={String(pending)}/><Metric icon="👥" label="Clientes" value={String(customers)}/></div><div className="pv-panels"><section className="pv-panel"><div className="pv-panel-head"><div><small>Operação</small><h2>Pedidos recentes</h2></div><button onClick={()=>setTab('orders')}>Ver todos <ExternalLink size={15}/></button></div><OrderTable rows={filtered.slice(0,8)} loading={loading} onStatus={updateStatus} onOpen={setSelected} saving={saving}/></section><section className="pv-panel pv-summary"><div className="pv-panel-head"><div><small>Resumo</small><h2>Status dos pedidos</h2></div></div>{statuses.map(s=>{const n=orders.filter(o=>o.status===s).length;return <div className="pv-status-row" key={s}><span>{s}</span><b>{n}</b></div>})}</section></div></>}
 {tab==='orders'&&<section className="pv-panel"><div className="pv-panel-head"><div><small>Gestão</small><h2>Todos os pedidos</h2></div><div className="pv-search"><Search size={16}/><input placeholder="Buscar pedido, cliente..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><OrderTable rows={filtered} loading={loading} onStatus={updateStatus} onOpen={setSelected} saving={saving}/></section>}
 {tab==='customers'&&<section className="pv-panel"><div className="pv-panel-head"><div><small>Relacionamento</small><h2>Clientes</h2></div></div><div className="pv-customer-grid">{Array.from(new Map(orders.map(o=>[o.customer_phone||o.customer_name,o])).values()).map(o=><div className="pv-customer" key={o.customer_phone||o.customer_name}><span>👤</span><div><b>{o.customer_name}</b><small>{o.customer_phone||'Telefone não informado'}</small><small>{o.city?`${o.city} - ${o.state}`:'Endereço não informado'}</small></div></div>)}</div>{!orders.length&&!loading&&<Empty text="Nenhum cliente ainda."/>}</section>}
 {tab==='products'&&<section className="pv-panel"><AdminProductManager/></section>}
 </div></main>{selected&&<OrderModal order={selected} close={()=>setSelected(null)} onStatus={updateStatus} saving={saving===selected.id}/>}</div>
}
function Metric({icon,label,value}:{icon:string;label:string;value:string}){return <div className="pv-metric"><span>{icon}</span><small>{label}</small><strong>{value}</strong></div>}
function Empty({text}:{text:string}){return <div className="pv-empty"><ShoppingBag size={30}/><b>{text}</b></div>}
function OrderTable({rows,loading,onStatus,onOpen,saving}:{rows:Order[];loading:boolean;onStatus:(id:number,s:string)=>void;onOpen:(o:Order)=>void;saving:number|null}){if(loading)return <div className="pv-loading"><RefreshCw className="spin"/> Carregando pedidos...</div>;if(!rows.length)return <Empty text="Nenhum pedido encontrado."/>;return <div className="pv-table-wrap"><table className="pv-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><b>#{o.id}</b></td><td><b>{o.customer_name}</b><small>{o.customer_phone}</small></td><td>{new Date(o.created_at).toLocaleString('pt-BR')}</td><td><b>{money(o.total)}</b></td><td><div className="pv-select"><select value={o.status} disabled={saving===o.id} onChange={e=>onStatus(o.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><ChevronDown size={14}/></div></td><td><button className="pv-view" onClick={()=>onOpen(o)}>Detalhes</button></td></tr>)}</tbody></table></div>}
function OrderModal({order,close,onStatus,saving}:{order:Order;close:()=>void;onStatus:(id:number,s:string)=>void;saving:boolean}){return <div className="pv-modal-back"><div className="pv-modal"><button className="pv-close" onClick={close}><XCircle/></button><small>Pedido #{order.id}</small><h2>{order.customer_name}</h2><p>{order.customer_phone}</p><div className="pv-order-total"><span>Total</span><b>{money(order.total)}</b></div><div className="pv-detail"><b>Itens</b>{(order.items||[]).map((x:any,i:number)=><div key={i}><span>{x.quantity||1}x {x.name}</span><b>{money(Number(x.price||0)*(x.quantity||1))}</b></div>)}</div><div className="pv-detail"><b>Entrega</b><p>{order.city?`${order.city} - ${order.state}`:'Endereço não informado'}</p><p>Forma de pagamento: {order.payment_method||'—'}</p></div><label className="pv-label">Status<select value={order.status} disabled={saving} onChange={e=>onStatus(order.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="pv-primary" onClick={close}><CheckCircle2 size={17}/> Concluir</button></div></div>}
