import { useEffect, useRef, useState } from 'react';
import { supabaseRest, SUPABASE_KEY, SUPABASE_URL } from './lib/supabase';
const bucket='product-images';
const empty={name:'',description:'',price:'',category:'Cães',stock:0,active:true,image_url:''};
const money=(n:number)=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function AdminProductManager(){
 const fileRef=useRef<HTMLInputElement>(null); const [products,setProducts]=useState<any[]>([]); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState<any>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [message,setMessage]=useState('');
 const load=async()=>{setLoading(true);try{const rows=await supabaseRest<any[]>('products?select=*&order=created_at.desc');setProducts(rows||[])}catch(e:any){setMessage(`Erro ao carregar produtos: ${e.message}`)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]); const reset=()=>{setEditing(null);setForm({...empty})}; const edit=(p:any)=>{setEditing(p);setForm({...empty,...p,price:p.price??''});window.scrollTo({top:0,behavior:'smooth'})};
 async function uploadPhoto(file:File){if(!file.type.startsWith('image/')){setMessage('Escolha JPG, PNG ou WebP.');return}if(file.size>5*1024*1024){setMessage('A foto deve ter no máximo 5 MB.');return}setUploading(true);setMessage('Enviando foto...');try{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${crypto.randomUUID()}-${Date.now()}.${ext}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':file.type,'x-upsert':'true'},body:file});if(!r.ok)throw new Error(await r.text());setForm((f:any)=>({...f,image_url:`${SUPABASE_URL}/storage/v1/object/public/${bucket}/${path}`}));setMessage('Foto enviada com sucesso.')}catch(e:any){setMessage(`Erro no upload: ${e.message}`)}finally{setUploading(false)}}
 async function save(e:any){e.preventDefault();if(!form.name.trim()){setMessage('Informe o nome do produto.');return}const price=Number(String(form.price).replace(',','.'));if(!Number.isFinite(price)||price<0){setMessage('Informe um preço válido.');return}setSaving(true);setMessage('Salvando...');try{const payload={name:form.name.trim(),description:form.description||'',price,category:form.category||'Geral',stock:Number(form.stock)||0,active:!!form.active,image_url:form.image_url||''};if(editing)await supabaseRest(`products?id=eq.${editing.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)});else await supabaseRest('products',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)});setMessage(editing?'Produto atualizado com sucesso!':'Produto adicionado com sucesso!');reset();await load()}catch(e:any){setMessage(`Erro ao salvar: ${e.message}`)}finally{setSaving(false)}}
 async function remove(id:number){if(!confirm('Excluir este produto?'))return;try{await supabaseRest(`products?id=eq.${id}`,{method:'DELETE'});setMessage('Produto excluído.');await load()}catch(e:any){setMessage(`Erro: ${e.message}`)}}
 async function toggle(p:any){try{await supabaseRest(`products?id=eq.${p.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({active:!p.active})});await load()}catch(e:any){setMessage(`Erro: ${e.message}`)}}
 return <section className="admin-products-manager" style={{display:'grid',gap:18}}><div className="admin-products-head"><div><h2>Produtos</h2><p>Adicione produtos, altere preços, fotos, estoque e disponibilidade.</p></div><button type="button" onClick={reset}>+ Novo produto</button></div>{message&&<div className="admin-product-message">{message}</div>}
 <form onSubmit={save} style={{display:'grid',gridTemplateColumns:'180px 1fr',gap:20,padding:20,border:'1px solid #eadfd6',borderRadius:20,background:'#fff'}}><div style={{display:'grid',gap:10,alignContent:'start'}}><div style={{height:160,borderRadius:16,overflow:'hidden',background:'#f7f2ed',display:'grid',placeItems:'center',border:'1px dashed #d8c9bc'}}>{form.image_url?<img src={form.image_url} alt="Produto" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<span style={{fontSize:42}}>📷</span>}</div><button type="button" disabled={uploading} onClick={()=>fileRef.current?.click()}>{uploading?'Enviando...':'📷 Alterar foto'}</button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)uploadPhoto(f)}}/></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do produto"/></label><label>Preço<input inputMode="decimal" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="R$ 0,00"/></label><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Cães','Gatos','Pássaros','Peixes','Roedores','Brinquedos','Acessórios','Higiene'].map(x=><option key={x}>{x}</option>)}</select></label><label>Estoque<input type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}>Descrição<textarea rows={3} value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={!!form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Visível na loja</label><div style={{display:'flex',gap:8,justifyContent:'flex-end'}}><button type="submit" disabled={saving||uploading}>{saving?'Salvando...':editing?'Salvar alterações':'Adicionar produto'}</button>{editing&&<button type="button" onClick={reset}>Cancelar</button>}</div></div></form>
 <div style={{display:'grid',gap:10}}>{loading?<p>Carregando produtos...</p>:products.length===0?<p>Nenhum produto cadastrado.</p>:products.map(p=><article key={p.id} style={{display:'grid',gridTemplateColumns:'72px 1fr auto auto auto auto',gap:14,alignItems:'center',padding:12,border:'1px solid #eadfd6',borderRadius:16,background:'#fff'}}><div style={{width:72,height:72,borderRadius:12,overflow:'hidden',background:'#f7f2ed',display:'grid',placeItems:'center'}}>{p.image_url?<img src={p.image_url} alt={p.name} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:'📷'}</div><div><strong>{p.name}</strong><small style={{display:'block',opacity:.65}}>{p.category} · estoque: {p.stock??0} · {p.active?'Ativo':'Oculto'}</small></div><strong>{money(p.price)}</strong><button type="button" onClick={()=>edit(p)}>Editar</button><button type="button" onClick={()=>toggle(p)}>{p.active?'Ocultar':'Ativar'}</button><button type="button" onClick={()=>remove(p.id)}>Excluir</button></article>)}</div></section>;
}
