import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowRight, BarChart3, Check, ChevronLeft, ChevronRight, LayoutDashboard, LogOut, Menu, Package, PawPrint, Plus, Search, ShoppingCart, Star, Trash2, UserPlus, Users, X } from "lucide-react";
import "./App.css";

type Product={id:number;name:string;category:string;price:number;stock:number;minStock:number;sku:string;rating:number;description:string;images:string[]};
type Customer={id:number;name:string;cpf:string;email:string;phone:string;city:string;createdAt:string;orders:number;spent:number};
type CartItem={product:Product;qty:number};
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const categories=["Todos","Ração","Petiscos","Brinquedos","Higiene","Acessórios","Camas","Coleiras e guias","Produtos para gatos","Produtos para cães"];
const photo=(id:string)=>`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1000&q=85`;
const seed:Product[]=[
{id:1,name:"Ração Premium Cães Adultos 15kg",category:"Ração",price:189.9,stock:18,minStock:8,sku:"RAC-15001",rating:4.9,description:"Nutrição completa e equilibrada para cães adultos.",images:[photo("1589924691995-400dc9ecc119"),photo("1552053831-71594a27632d"),photo("1583337130417-3346a1be7dee")]},
{id:2,name:"Ração Gatos Castrados 10kg",category:"Produtos para gatos",price:139.9,stock:7,minStock:8,sku:"GAT-10002",rating:4.8,description:"Fórmula especial para gatos castrados e controle de peso.",images:[photo("1519052537078-e6302a4968d4"),photo("1574158622682-e40e69881006"),photo("1518791841217-8f162f1e1131")]},
{id:3,name:"Brinquedo Interativo Mordedor",category:"Brinquedos",price:39.9,stock:31,minStock:5,sku:"BRI-00031",rating:4.7,description:"Diversão e estímulo mental para brincadeiras do dia a dia.",images:[photo("1601758174114-e711c0cbaa69"),photo("1558929996-da64ba858215"),photo("1560743641-4c3c2a8f5e7f")]},
{id:4,name:"Cama Premium Nuvem",category:"Camas",price:129.9,stock:5,minStock:5,sku:"CAM-00441",rating:4.9,description:"Cama macia e confortável com acabamento premium.",images:[photo("1591946614720-90a587da4a36"),photo("1548199973-03cce0bbc87b"),photo("1601758123927-196b4c2d8e7a")]},
{id:5,name:"Kit Higiene Completo",category:"Higiene",price:59.9,stock:22,minStock:5,sku:"HIG-00025",rating:4.6,description:"Kit completo para a rotina de higiene do seu pet.",images:[photo("1583337130417-3346a1be7dee"),photo("1558788353-f76d92427f16"),photo("1583512603805-3cc6b41f3ed7")]},
{id:6,name:"Coleira Comfort Ajustável",category:"Coleiras e guias",price:49.9,stock:14,minStock:4,sku:"COL-00118",rating:4.8,description:"Coleira confortável, resistente e ajustável.",images:[photo("1558788353-f76d92427f16"),photo("1591369822096-ffd140ec948f"),photo("1583337130417-3346a1be7dee")]}
];
const customerSeed:Customer[]=[{id:1,name:"Mariana Costa",cpf:"***.***.***-01",email:"mariana@email.com",phone:"(34) 98888-1001",city:"Uberaba - MG",createdAt:"13/08/2026",orders:8,spent:1249.7},{id:2,name:"João Henrique",cpf:"***.***.***-42",email:"joao@email.com",phone:"(34) 97777-2002",city:"Uberaba - MG",createdAt:"12/08/2026",orders:4,spent:689.9}];
const load=<T,>(key:string,fallback:T):T=>{try{const x=localStorage.getItem(key);return x?JSON.parse(x):fallback}catch{return fallback}};

export default function App(){
 const[admin,setAdmin]=useState(false),[products,setProducts]=useState<Product[]>(()=>load("petviva_products",seed)),[customers,setCustomers]=useState<Customer[]>(()=>load("petviva_customers",customerSeed)),[cart,setCart]=useState<CartItem[]>([]),[cat,setCat]=useState("Todos"),[query,setQuery]=useState(""),[gallery,setGallery]=useState<Product|null>(null),[cartOpen,setCartOpen]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>localStorage.setItem("petviva_products",JSON.stringify(products)),[products]);useEffect(()=>localStorage.setItem("petviva_customers",JSON.stringify(customers)),[customers]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2300)};const list=useMemo(()=>products.filter(p=>(cat==="Todos"||p.category===cat)&&p.name.toLowerCase().includes(query.toLowerCase())),[products,cat,query]);
 const add=(p:Product)=>{setCart(c=>{const f=c.find(x=>x.product.id===p.id);return f?c.map(x=>x.product.id===p.id?{...x,qty:Math.min(p.stock,x.qty+1)}:x):[...c,{product:p,qty:1}]});notify("Produto adicionado ao carrinho")};
 if(admin)return <Admin products={products} setProducts={setProducts} customers={customers} setCustomers={setCustomers} exit={()=>setAdmin(false)} notify={notify}/>;
 return <div className="site-shell"><header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>scrollTo(0,0)}><span><PawPrint/></span><b>Pet</b><em>Viva</em></button><nav><button onClick={()=>scrollTo(0,0)}>Início</button><button onClick={()=>document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})}>Produtos</button><button onClick={()=>notify("Agenda disponível no painel")}>Serviços</button></nav><div className="header-actions"><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produtos..."/></div><button className="cart-btn" onClick={()=>setCartOpen(true)}><ShoppingCart/> Carrinho {cart.length>0&&<b>{cart.reduce((s,x)=>s+x.qty,0)}</b>}</button><button className="menu-btn"><Menu/></button></div></div></header><main><section className="hero"><div className="hero-copy"><span className="eyebrow">Cuidado que seu pet merece</span><h1>Mais carinho.<br/><strong>Mais vida.</strong><br/>Para quem faz parte da família.</h1><p>Produtos selecionados e uma experiência pensada para cuidar do seu melhor amigo.</p><button className="primary" onClick={()=>document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})}>Comprar agora <ArrowRight/></button></div><div className="hero-visual"><div className="pet-photo"><img src={photo("1552053831-71594a27632d")} alt="Cachorro feliz"/></div></div></section><section className="benefits"><Benefit title="Frete grátis" text="Acima de R$ 199"/><Benefit title="Compra segura" text="Dados protegidos"/><Benefit title="Curadoria premium" text="Produtos selecionados"/><Benefit title="Atendimento" text="Perto de você"/></section><section className="section" id="catalogo"><div className="section-heading"><div><span className="eyebrow">Nossa seleção</span><h2>Tudo para o seu pet</h2><p>Escolha seus produtos favoritos.</p></div></div><div className="category-strip">{categories.map(c=><button className={cat===c?"active":""} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="product-grid">{list.map(p=><ProductCard key={p.id} product={p} open={()=>setGallery(p)} add={()=>add(p)}/>)}</div></section></main><footer className="footer"><div className="footer-main"><div><div className="brand"><span><PawPrint/></span><b>Pet</b><em>Viva</em></div><p>Cuidado, carinho e tudo o que seu pet precisa.</p></div><div><h4>Atendimento</h4><span>Uberaba · MG</span><span>contato@petviva.com.br</span></div></div><div className="footer-bottom"><span>© 2026 PetViva</span><button onClick={()=>setAdmin(true)}>Acesso administrativo</button></div></footer>{gallery&&<Gallery product={gallery} close={()=>setGallery(null)} add={()=>{add(gallery);setGallery(null)}}/>}{cartOpen&&<Cart cart={cart} setCart={setCart} close={()=>setCartOpen(false)}/>} {toast&&<div className="toast"><Check/>{toast}</div>}</div>;
}
function Benefit({title,text}:{title:string;text:string}){return <div className="benefit"><span><Check/></span><div><strong>{title}</strong><small>{text}</small></div></div>}
function ProductCard({product,open,add}:{product:Product;open:()=>void;add:()=>void}){return <article className="product-card"><button className="product-image" onClick={open}><img src={product.images[0]} alt={product.name}/><span className="quick-view">3 fotos · Ver detalhes</span></button><div className="product-content"><small>{product.category}</small><button className="product-name" onClick={open}>{product.name}</button><span className="rating"><Star fill="currentColor"/> {product.rating}</span><div className="product-bottom"><strong>{money(product.price)}</strong><button className="add-btn" onClick={add}><Plus/> Adicionar</button></div></div></article>}
function Gallery({product,close,add}:{product:Product;close:()=>void;add:()=>void}){const[i,setI]=useState(0);return <div className="modal-backdrop" onClick={close}><div className="product-modal gallery-modal" onClick={e=>e.stopPropagation()}><button className="close-btn" onClick={close}><X/></button><div className="gallery"><img src={product.images[i]} alt={product.name}/><button onClick={()=>setI((i+2)%3)}><ChevronLeft/></button><button onClick={()=>setI((i+1)%3)}><ChevronRight/></button><div className="thumbs">{product.images.map((x,n)=><button className={n===i?"selected":""} key={x} onClick={()=>setI(n)}><img src={x} alt=""/></button>)}</div></div><div className="modal-copy"><span className="eyebrow">{product.category}</span><h2>{product.name}</h2><span className="rating"><Star fill="currentColor"/> {product.rating} · avaliações</span><h3>{money(product.price)}</h3><p>{product.description}</p><div className="spec-grid"><span><small>SKU</small><b>{product.sku}</b></span><span><small>Estoque</small><b>{product.stock}</b></span><span><small>Fotos</small><b>3</b></span></div><button className="primary full" onClick={add}>Adicionar ao carrinho <ShoppingCart/></button></div></div></div>}
function Cart({cart,setCart,close}:{cart:CartItem[];setCart:React.Dispatch<React.SetStateAction<CartItem[]>>;close:()=>void}){const total=cart.reduce((s,x)=>s+x.product.price*x.qty,0);return <div className="drawer-backdrop" onClick={close}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><h2>Seu carrinho</h2><button className="close-btn" onClick={close}><X/></button></div>{cart.length?cart.map(x=><div className="cart-line" key={x.product.id}><img src={x.product.images[0]} alt=""/><div><b>{x.product.name}</b><small>{money(x.product.price)}</small><div className="qty-control"><button onClick={()=>setCart(c=>c.map(y=>y.product.id===x.product.id?{...y,qty:Math.max(1,y.qty-1)}:y))}><Minus/></button><b>{x.qty}</b><button onClick={()=>setCart(c=>c.map(y=>y.product.id===x.product.id?{...y,qty:Math.min(x.product.stock,y.qty+1)}:y))}><Plus/></button><button onClick={()=>setCart(c=>c.filter(y=>y.product.id!==x.product.id))}><Trash2/></button></div></div></div>):<div className="empty-state">Seu carrinho está vazio.</div>}<div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary full" disabled={!cart.length} onClick={()=>alert("Checkout conectado ao próximo módulo.")}>Finalizar compra <ArrowRight/></button></aside></div>}

function Admin({products,setProducts,customers,setCustomers,exit,notify}:{products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;customers:Customer[];setCustomers:React.Dispatch<React.SetStateAction<Customer[]>>;exit:()=>void;notify:(s:string)=>void}){const[tab,setTab]=useState<"dashboard"|"products"|"customers">("dashboard");const[search,setSearch]=useState("");const[productModal,setProductModal]=useState(false);const[customerModal,setCustomerModal]=useState(false);const[editing,setEditing]=useState<Product|null>(null);return <div className="admin-shell"><aside className="admin-sidebar"><button className="admin-brand" onClick={()=>setTab("dashboard")}><span><PawPrint/></span><b>Pet</b><em>Viva</em></button><button className={tab==="dashboard"?"active":""} onClick={()=>setTab("dashboard")}><LayoutDashboard/> Visão geral</button><button className={tab==="products"?"active":""} onClick={()=>setTab("products")}><Package/> Produtos</button><button className={tab==="customers"?"active":""} onClick={()=>setTab("customers")}><Users/> Clientes</button><button className="admin-exit" onClick={exit}><LogOut/> Voltar à loja</button></aside><div className="admin-main"><header className="admin-topbar"><div><span className="eyebrow">Painel administrativo</span><h1>{tab==="dashboard"?"Visão geral":tab==="products"?"Produtos":"Clientes"}</h1></div></header><main className="admin-content">{tab==="dashboard"&&<Dashboard products={products} customers={customers} setTab={setTab}/>} {tab==="products"&&<Products products={products} search={search} setSearch={setSearch} newProduct={()=>{setEditing(null);setProductModal(true)}} edit={p=>{setEditing(p);setProductModal(true)}} remove={p=>{if(confirm(`Excluir ${p.name}?`))setProducts(x=>x.filter(y=>y.id!==p.id))}}/>}{tab==="customers"&&<Customers customers={customers} search={search} setSearch={setSearch} newCustomer={()=>setCustomerModal(true)} remove={c=>{if(confirm(`Excluir ${c.name}?`))setCustomers(x=>x.filter(y=>y.id!==c.id))}}/>}</main></div>{productModal&&<ProductEditor product={editing} close={()=>setProductModal(false)} save={p=>{setProducts(x=>editing?x.map(y=>y.id===editing.id?p:y):[...x,p]);setProductModal(false);notify(editing?"Produto atualizado":"Produto cadastrado")}}/>}{customerModal&&<CustomerEditor close={()=>setCustomerModal(false)} save={c=>{setCustomers(x=>[c,...x]);setCustomerModal(false);notify("Cliente cadastrado")}}/>}</div>}
function Dashboard({products,customers,setTab}:{products:Product[];customers:Customer[];setTab:(x:"dashboard"|"products"|"customers")=>void}){return <><div className="metrics-grid"><Metric icon={<Package/>} label="Produtos" value={String(products.length)}/><Metric icon={<Users/>} label="Clientes" value={String(customers.length)}/><Metric icon={<BarChart3/>} label="Estoque" value={String(products.reduce((s,p)=>s+p.stock,0))}/><Metric icon={<ShoppingCart/>} label="SKUs baixos" value={String(products.filter(p=>p.stock<=p.minStock).length)}/></div><div className="admin-grid"><div className="admin-panel module-empty"><Package/><h2>Catálogo</h2><p>Cadastre produtos, preços, estoque e 3 fotos por produto.</p><button className="primary" onClick={()=>setTab("products")}>Gerenciar produtos <ArrowRight/></button></div><div className="admin-panel module-empty"><Users/><h2>CRM</h2><p>Cadastre clientes e mantenha os dados organizados.</p><button className="primary" onClick={()=>setTab("customers")}>Gerenciar clientes <ArrowRight/></button></div></div></>}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="metric-card"><span>{icon}</span><small>{label}</small><strong>{value}</strong></div>}
function Products({products,search,setSearch,newProduct,edit,remove}:{products:Product[];search:string;setSearch:(s:string)=>void;newProduct:()=>void;edit:(p:Product)=>void;remove:(p:Product)=>void}){return <div className="module-view"><div className="view-toolbar"><div><span className="eyebrow">Catálogo</span><h2>Produtos</h2><p>Crie e edite produtos com galeria de 3 fotos.</p></div><button className="primary" onClick={newProduct}><Plus/> Novo produto</button></div><div className="toolbar-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto"/></div><div className="admin-panel table-panel"><table><thead><tr><th>PRODUTO</th><th>CATEGORIA</th><th>PREÇO</th><th>ESTOQUE</th><th>FOTOS</th><th>AÇÕES</th></tr></thead><tbody>{products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><tr key={p.id}><td><div className="table-product"><img src={p.images[0]} alt=""/><span><b>{p.name}</b><small>{p.sku}</small></span></div></td><td>{p.category}</td><td>{money(p.price)}</td><td>{p.stock}</td><td>{p.images.length}</td><td><button onClick={()=>edit(p)}>Editar</button> <button className="danger" onClick={()=>remove(p)}>Excluir</button></td></tr>)}</tbody></table></div></div>}
function ProductEditor({product,close,save}:{product:Product|null;close:()=>void;save:(p:Product)=>void}){const[p,setP]=useState<Product>(product||{id:Date.now(),name:"",category:"Ração",price:0,stock:0,minStock:5,sku:"",rating:5,description:"",images:["","",""]});const set=(k:keyof Product,v:string|number)=>setP(x=>({...x,[k]:v}));return <div className="modal-backdrop"><div className="editor-modal"><button className="close-btn" onClick={close}><X/></button><span className="eyebrow">Catálogo</span><h2>{product?"Editar produto":"Cadastrar produto"}</h2><div className="form-grid"><label className="wide">Nome<input value={p.name} onChange={e=>set("name",e.target.value)}/></label><label>Categoria<select value={p.category} onChange={e=>set("category",e.target.value)}>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>SKU<input value={p.sku} onChange={e=>set("sku",e.target.value)}/></label><label>Preço<input type="number" value={p.price} onChange={e=>set("price",Number(e.target.value))}/></label><label>Estoque<input type="number" value={p.stock} onChange={e=>set("stock",Number(e.target.value))}/></label><label>Estoque mínimo<input type="number" value={p.minStock} onChange={e=>set("minStock",Number(e.target.value))}/></label><label className="wide">Descrição<textarea value={p.description} onChange={e=>set("description",e.target.value)}/></label></div><div className="image-fields"><b>Galeria do produto · 3 fotos</b>{p.images.map((u,i)=><label key={i}>Foto {i+1}<input value={u} onChange={e=>setP(x=>({...x,images:x.images.map((a,n)=>n===i?e.target.value:a)}))} placeholder="https://..."/>{u&&<img src={u} alt="Prévia"/>}</label>)}</div><button className="primary full" disabled={!p.name||p.price<=0||p.images.filter(Boolean).length<3} onClick={()=>save({...p,images:p.images.filter(Boolean).slice(0,3)})}><Check/> Salvar produto</button></div></div>}
function Customers({customers,search,setSearch,newCustomer,remove}:{customers:Customer[];search:string;setSearch:(s:string)=>void;newCustomer:()=>void;remove:(c:Customer)=>void}){return <div className="module-view"><div className="view-toolbar"><div><span className="eyebrow">CRM</span><h2>Clientes</h2><p>Cadastre clientes e consulte os dados de relacionamento.</p></div><button className="primary" onClick={newCustomer}><UserPlus/> Novo cliente</button></div><div className="toolbar-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome, e-mail ou telefone"/></div><div className="admin-panel table-panel"><table><thead><tr><th>CLIENTE</th><th>CONTATO</th><th>CIDADE</th><th>PEDIDOS</th><th>TOTAL GASTO</th><th>CADASTRO</th><th></th></tr></thead><tbody>{customers.filter(c=>`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.id}><td><div className="customer-cell"><span>{c.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><b>{c.name}</b><small>{c.cpf||"CPF não informado"}</small></div></div></td><td>{c.email}<small>{c.phone}</small></td><td>{c.city}</td><td>{c.orders}</td><td>{money(c.spent)}</td><td>{c.createdAt}</td><td><button className="danger" onClick={()=>remove(c)}>Excluir</button></td></tr>)}</tbody></table></div></div>}
function CustomerEditor({close,save}:{close:()=>void;save:(c:Customer)=>void}){const[c,setC]=useState({name:"",cpf:"",email:"",phone:"",city:""});return <div className="modal-backdrop"><div className="editor-modal"><button className="close-btn" onClick={close}><X/></button><span className="eyebrow">CRM</span><h2>Cadastrar cliente</h2><div className="form-grid"><label className="wide">Nome completo<input value={c.name} onChange={e=>setC({...c,name:e.target.value})}/></label><label>CPF<input value={c.cpf} onChange={e=>setC({...c,cpf:e.target.value})}/></label><label>Telefone<input value={c.phone} onChange={e=>setC({...c,phone:e.target.value})}/></label><label className="wide">E-mail<input type="email" value={c.email} onChange={e=>setC({...c,email:e.target.value})}/></label><label className="wide">Cidade / UF<input value={c.city} onChange={e=>setC({...c,city:e.target.value})} placeholder="Uberaba - MG"/></label></div><button className="primary full" disabled={!c.name||!c.email} onClick={()=>save({id:Date.now(),...c,createdAt:new Date().toLocaleDateString("pt-BR"),orders:0,spent:0})}><UserPlus/> Cadastrar cliente</button></div></div>}
